spring.application.name=backend
# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/lab4-spring-vue
spring.datasource.username=admin
spring.datasource.password=1234567890

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hikari CP
spring.datasource.hikari.maximum-pool-size=8